Feature:Final step
NickEmma/hello-rails-react pull request #1
Opened 2022-11-21 11:40 UTC by NickEmma

Greetings 👋🏻
Thanks for taking the time to review my code

Changes implemented
✅ Create rails react single application
✅ Create Greeting API endpoint (api/v1/greeting)
✅ Create a Greeting route using React
✅ Create a redux store, action, and a reducer to fetch the data from the API ('/greeting')

2022-11-21 11:58 UTC, GzimAsani requested changes
### Hello  @NickEmma           :wave:   
 Good job so far! There are some issues that you still need to work on to go to the next project but you are almost there!
 
 ## Highlights
 * Good job with implementing react router :+1: 

 ## Required Changes 


- [ ] Please add a professional readme by using the Microverse [template](https://github.com/microverseinc/readme-template)
- [ ] Check the comment below :arrow_double_down: 



 ## Optional suggestions
 _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding! clapclapclap
 
 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
 
 **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
 
 _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-21 11:58 UTC, GzimAsani commented on app/views/api/v1/greetings/index.json.jbuilder
> +json.text @greeting.text
- [ ] I am getting an error when visiting the index page, kindly update it ![image](https://user-images.githubusercontent.com/62705947/203046369-b6cca732-25de-49aa-86db-1e5eccd0cdfb.png)

2022-11-22 08:46 UTC, brytebee requested changes
Hi, @NickEmma👋, 

##

### Highlights💡
- Good commit message.✔️ 
- Good PR Summary.✔️
- Great UI design.✔️
- App functions as it should.✔️

##

Great work on making the changes 👏 👏 
You've done well implementing some of the requested changes requested by the previous review, but there are still some which aren't addressed yet.


# Suggested changes
_Check the comments under the review._

![](https://media.giphy.com/media/VlqzeaRnhCvPLfrSh6/giphy.gif)


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @brytebee in your question so I can receive the notification.
### _**Use @brytebee on slack for faster responses.**_

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-11-22 08:46 UTC, brytebee commented on app/views/api/v1/greetings/index.json.jbuilder
> +json.text @greeting.text
Just like this previous review, I am getting the same error.
![image](https://user-images.githubusercontent.com/27709832/203266090-c63943a0-f190-4905-b944-fe9c4e0f569c.png)

Kindly research more about Jbuilder syntax and usage to render your views.

2022-11-22 08:57 UTC, NickEmma commented on app/views/api/v1/greetings/index.json.jbuilder
> +json.text @greeting.text
@brytebee i am on windows and i specified it on the readme. it's working fine and i don't know why you requested for changes.

2022-11-22 09:50 UTC, julie-ify approved these changes
Hi @NickEmma,

## Highlights!
- Good feature branch name ✔️ 
- No linter errors ✔️ 
- Descriptive pull request ✔️ 
- Descriptive commit messages ✔️ 
- Good code organization and working app ✔️
- Descriptive README ✔️ 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# Status: Approved ✔️ 

Cheers and Happy coding!👏👏👏

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-22 09:52 UTC, merged